modLoader="javafml"
loaderVersion="[41,)"
license="All rights reserved"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/tool-upgrades/issues"

[[mods]]
modId="toolupgrades"
version="3.0.3"
displayName="ToolUpgrades"
updateJSONURL="https://raw.githubusercontent.com/XxRexRaptorxX/Update-Checker/main/ToolUpgrades.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/tool-upgrades"
logoFile="logo.png"
credits=""
authors="XxRexRaptorxX (RexRaptor)"
description='''
With this mod can you upgrade your tools and weapons with modifiers!
'''

[[dependencies.toolupgrades]]
    modId="forge"
    mandatory=true
versionRange="[41.0.98,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.toolupgrades]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
